### ISSUE TITLE
(T) Не реализовано требование FR005

### ISSUE THREAD

**Issue by ikit-mita** [SMOuk/HomeWork1-2version#1]
> Система должна позволять изменить цвет кошки

Система должна запросить цвет для здоровой и для больной кошки и заменить белый и зеленый на значения, введенные пользователем

> Вы выбрали изменение цвета
> Введите цвет здоровой кошки
> Черный
> Введите цвет больной кошки
> Синий

**Comment by SMOuk** [comment]
Исправил, не стал перезаливать проект полностью изменил в редакторе класс CatColor, теперь он статичный и его поля тоже (можно обращаться без создания экземпляра, через имя класса)

Класс Cats тоже изменил (убрал создаваемый экземпляр класса CatColor и обращение к полям класса CatColor)

 В классе Program добавил пункт меню - «Поменять цвет здоровой и больной кошки»
